### ISSUE TITLE
Add open source license for py-rbush

### ISSUE THREAD

**Issue by yungyuc** [lebr0nli/py-rbush#1]
@lebr0nli , please add an open source license for your project. If you are not sure how to do it, see https://github.com/solvcon/modmesh.

**Comment by yungyuc** [comment]
@lebr0nli any update?

**Comment by lebr0nli** [comment]
Thanks!
Should be resolved now. Let me know if there's any issue with the LICENSE.

**Comment by yungyuc** [comment]
LGTM
