### ISSUE TITLE
Would nightly CI run help your development?

### ISSUE THREAD

**Issue by yungyuc** [lebr0nli/py-rbush#13]
A nightly CI run helps developers to establish a baseline for the code status without any change (except the dependencies and environment).  For a large project it is a must.

It may or may not provide significant productivity for a small project like yours, but won't be useless.  You can take a look at https://github.com/solvcon/modmesh/actions for how it works.  Feel free to discuss with me.

**Comment by lebr0nli** [comment]
Yes, I think this should help my development, and even if it doesn't, it'll be good practice for me.
I'll try to do this, thanks for the advice!
