### ISSUE TITLE
Progress with prototype and testing

### ISSUE THREAD

**Issue by yungyuc** [lebr0nli/py-rbush#3]
@lebr0nli Based on [your schedule](https://github.com/yungyuc/nsdhw_24au/blob/ed6f48bf0412b8a5f9324cd055c49a4906700e8c/project/lebr0nli/README.rst?plain=1#L192), there may be some prototyping code and testing ready.  Could you please update what you have done so far?

**Comment by lebr0nli** [comment]
I just updated my progress with #3, which introduces the basic infrastructure to ensure the project can be built and tested effectively.
I will focus on implementing the `RBush` class in [_rbush/](https://github.com/lebr0nli/py-rbush/tree/main/_rbush) next.

**Comment by yungyuc** [comment]
LGTM!
